### PR TITLE
Adds support for my vanish-plugins

### PR DESCRIPTION
**Pull request by LeonMangler**
SuperVanish(v5.4.0+)
and PremiumVanish(upcoming)
https://www.spigotmc.org/resources/supervanish.1331/

### CODE REVIEW

**Comment by JamieSinn** [comment]
Why these and not something generic and why no imports

**Comment by JamieSinn** [comment]
Also, you didn't test this as it has no maven dependency

**Comment by LeonMangler** [comment]
It's just a suggestion if you'd like to change it go ahead.
I don't think there's a generic way since we can't use getHiddenPlayers() from player.spigot because your system doesn't use packets to make the particles client-side and removing the trail for every player wouldn't support hub-plugins.
Not sure if testing it is required since it uses really simple code.
It's your plugin, I can just remove your trails by using packets or hooking into your code, too, this would just be easier and save my time.

**Comment by JamieSinn** [comment]
My point is that this will not compile right now, look into maven dependencies

**Comment by LeonMangler** [comment]
Uh never really used maven, I think you can do that yourself.

**Comment by JamieSinn** [comment]
I like the idea at the core, but I think something like getting all online players and checking can see would be better

**Comment by LeonMangler** [comment]
That won't quite work as I've already mentioned since your particles aren't per-player/client-side and removing the trail for everyone because one player cannot see the player would be non-sense since it'd break every hub-plugin (magic clock, etc).
The best solution (imo) would be an event like ParticleDisplayEvent or something like that.

Edit: You can't just check if everyone can't see the player because most of the vanish-plugins have a permission for seeing every player.

**Comment by JamieSinn** [comment]
I'll look into this. 
See what else is going on.

**Comment by LeonMangler** [comment]
Why didn't you just add support for essentials' vanish-system?
Nearly every vanish-plugin hooks into it, you would've added support for at least 10 vanish-plugins with a few lines of code.

**Comment by JamieSinn** [comment]
Because not all servers that run this run essentials

**Comment by JamieSinn** [comment]
Though I will keep it in mind for the future

**Comment by LeonMangler** [comment]
OK I'll just reregister your move event then to add support for supervanish and premiumvanish.

**Comment by JamieSinn** [comment]
I'm planning on making an api stay tuned

**Pull request closed without merging**
