### PR TITLE
Update to 1.16.1

### PR DESCRIPTION
**Pull request by JohnStar128**
- [x] Add 1.16.1 Support.
- [x] Change Bukkit API dependency to Spigot API.
- [x] Increment API version.
- [x] Add Bubble Column Up trail.
- [x] Add Bubble Pop trail.
- [x] Add Current Down trail.
- [x] Add Cosy Campfire trail.
- [x] Add Signal Campfire trail.
- [x] Add Sneeze trail.
- [x] Add Dripping Honey trail.
- [x] Add Falling Nectar trail.
- [x] Add Dripping Obsidian trail.
- [x] Add Ash trail.
- [x] Add Crimson Spore trail.
- [x] Add Warped Spore trail.
- [x] Add Soul Fire trail.
- [x] Add Soul trail.
- [x] Few random cleanups.

### CODE REVIEW

**Comment by JamieSinn** [comment]
Seems like the maven depend is incorrect. 

https://github.com/SinnDevelopment/TrailGUI/runs/891424249?check_suite_focus=true#step:4:88

I believe the new format is `spigot-api`

**Comment by JohnStar128** [comment]
A friend of mine literally just pointed that out, fixed.

**Comment by JohnStar128** [comment]
Three out of the four particles 1.13 added are effectively the same particle, but I added all three anyway. Also in a case where there's three variants of the same type of particle (e.g. dripping honey, falling honey and landing honey), I picked only the one with the best visual appeal.

**Comment by JamieSinn** [comment]
Make sure you update the unit testing config: 
https://github.com/SinnDevelopment/TrailGUI/blob/master/src/test/resources/config.yml
It should be a quick copy paste for the new section values.

**Pull request merged**
